Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/initializers/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'
    - 'bin/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'
